version: '3'

services:
  app:
    ports:
      - '80:80'
      - '5173:5173'
    build:
      context: ./docker
      dockerfile: 'Dockerfile.dev'
    container_name: app
    volumes:
      - ./src:/var/www/html
      - node_modules:/var/www/html/mini-journal/node_modules
    depends_on:
      - db
      - mailpit
  db:
    image: mysql:8.0.30
    container_name: db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'

volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      device: ${NODE_MODULES_DIRECTORY}
      o: bind
